import json
from pathlib import Path

import pandas as pd
import streamlit as st


# ============================================================
# PROJECT PATHS
# ============================================================

ROOT = Path(__file__).resolve().parent
RESULTS = ROOT / "results"
FIGURES = ROOT / "figures"


# ============================================================
# STREAMLIT CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="Quantum Materials ML",
    page_icon="🔬",
    layout="wide",
)


# ============================================================
# DATA LOADING FUNCTIONS
# ============================================================

@st.cache_data
def load_predictions():
    """
    Load predictions generated by the all-material screening script.
    """
    path = RESULTS / "all_material_predictions.csv"

    if not path.exists():
        return pd.DataFrame()

    return pd.read_csv(path)


@st.cache_data
def load_metrics():
    """
    Load final model test metrics.
    """
    path = RESULTS / "final_model_metrics.json"

    if not path.exists():
        return {}

    try:
        return json.loads(path.read_text())
    except Exception:
        return {}


@st.cache_data
def load_group_metrics():
    """
    Load chemical-system GroupKFold validation metrics.
    """
    path = RESULTS / "tuned_groupkfold_summary.json"

    if not path.exists():
        return {}

    try:
        return json.loads(path.read_text())
    except Exception:
        return {}


@st.cache_data
def load_trustworthiness():
    """
    Load trustworthy-ML summary generated by Notebook 06.
    """
    path = RESULTS / "advanced_trustworthiness_summary.json"

    if not path.exists():
        return {}

    try:
        return json.loads(path.read_text())
    except Exception:
        return {}


@st.cache_data
def load_permutation_importance():
    """
    Load permutation feature importance.
    """
    path = RESULTS / "advanced_permutation_importance.csv"

    if not path.exists():
        return pd.DataFrame()

    try:
        return pd.read_csv(path)
    except Exception:
        return pd.DataFrame()


@st.cache_data
def load_shap_importance():
    """
    Load SHAP feature importance.
    """
    path = RESULTS / "shap_feature_importance.csv"

    if not path.exists():
        return pd.DataFrame()

    try:
        return pd.read_csv(path)
    except Exception:
        return pd.DataFrame()


@st.cache_data
def load_structural_importance():
    """
    Load structural-feature importance generated by Notebook 08.
    """
    path = RESULTS / "structural_feature_importance.csv"

    if not path.exists():
        return pd.DataFrame()

    try:
        return pd.read_csv(path)
    except Exception:
        return pd.DataFrame()


@st.cache_data
def load_final_model_comparison():
    """
    Load the actual model-comparison output generated by Notebook 09.
    """
    path = RESULTS / "final_model_comparison.csv"

    if not path.exists():
        return pd.DataFrame()

    try:
        return pd.read_csv(path)
    except Exception:
        return pd.DataFrame()


@st.cache_data
def load_structural_model_comparison():
    """
    Load the structure-aware comparison generated by Notebook 09.
    """
    path = RESULTS / "structural_model_comparison.csv"

    if not path.exists():
        return pd.DataFrame()

    try:
        return pd.read_csv(path)
    except Exception:
        return pd.DataFrame()


@st.cache_data
def load_final_research_summary():
    """
    Load the final research summary generated by Notebook 09.
    """
    path = RESULTS / "final_research_summary.json"

    if not path.exists():
        return {}

    try:
        return json.loads(path.read_text())
    except Exception:
        return {}


@st.cache_data
def load_advanced_model_comparison():
    """
    Load the advanced model-comparison output generated by Notebook 10.
    """
    path = RESULTS / "advanced_model_comparison.csv"

    if not path.exists():
        return pd.DataFrame()

    try:
        return pd.read_csv(path)
    except Exception:
        return pd.DataFrame()


@st.cache_data
def load_hypothetical_candidates():
    """Load hypothetical composition candidates generated by the discovery script."""
    path = RESULTS / "hypothetical_candidates.csv"

    if not path.exists():
        return pd.DataFrame()

    try:
        return pd.read_csv(path)
    except Exception:
        return pd.DataFrame()


# ============================================================
# LOAD PROJECT DATA
# ============================================================

metrics = load_metrics()
group_metrics = load_group_metrics()
predictions = load_predictions()
trust = load_trustworthiness()
perm = load_permutation_importance()
shap_df = load_shap_importance()
structural_importance = load_structural_importance()

final_model_comparison = load_final_model_comparison()
structural_model_comparison = load_structural_model_comparison()
final_research_summary = load_final_research_summary()
advanced_model_comparison = load_advanced_model_comparison()
hypothetical_candidates = load_hypothetical_candidates()


# ============================================================
# HEADER
# ============================================================

st.title(
    "Machine-Learning-Assisted Discovery of Quantum Materials"
)

st.caption(
    "JARVIS-DFT 3D • OptB88vdW band-gap prediction • "
    "Random Forest • Composition + Structure-aware ML"
)


# ============================================================
# TABS
# ============================================================

tab1, tab2, tab3, tab4, tab5, tab6, tab7, tab8 = st.tabs(
    [
        "Model performance",
        "Candidate screening",
        "Trustworthiness",
        "Structure-aware ML",
        "Model comparison",
        "Advanced optimization",
        "Hypothetical discovery",
        "About",
    ]
)


# ============================================================
# TAB 1 — MODEL PERFORMANCE
# ============================================================

with tab1:

    st.subheader("Final model performance")

    c1, c2, c3 = st.columns(3)

    c1.metric(
        "Test MAE",
        f"{metrics.get('test_MAE_eV', 0):.3f} eV",
    )

    c2.metric(
        "Test RMSE",
        f"{metrics.get('test_RMSE_eV', 0):.3f} eV",
    )

    c3.metric(
        "Test R²",
        f"{metrics.get('test_R2', 0):.3f}",
    )

    # --------------------------------------------------------
    # MATERIALS-AWARE VALIDATION
    # --------------------------------------------------------

    st.markdown("### Materials-aware validation")

    g1, g2, g3 = st.columns(3)

    g1.metric(
        "GroupKFold MAE",
        f"{group_metrics.get('MAE_mean_eV', 0):.3f} ± "
        f"{group_metrics.get('MAE_std_eV', 0):.3f} eV",
    )

    g2.metric(
        "GroupKFold RMSE",
        f"{group_metrics.get('RMSE_mean_eV', 0):.3f} ± "
        f"{group_metrics.get('RMSE_std_eV', 0):.3f} eV",
    )

    g3.metric(
        "GroupKFold R²",
        f"{group_metrics.get('R2_mean', 0):.3f} ± "
        f"{group_metrics.get('R2_std', 0):.3f}",
    )

    st.info(
        "The random test split measures interpolation on a held-out "
        "subset. Chemical-system GroupKFold is stricter: related "
        "chemical systems are kept out of the training fold."
    )

    # --------------------------------------------------------
    # MODEL DESCRIPTION
    # --------------------------------------------------------

    st.markdown("### What the model predicts")

    st.write(
        "The model predicts the JARVIS-DFT OptB88vdW band gap in eV "
        "using composition-derived atomic descriptors and "
        "crystal-structure information. HSE/MBJ band gaps are not "
        "used as input features."
    )


# ============================================================
# TAB 2 — CANDIDATE SCREENING
# ============================================================

with tab2:

    st.subheader("Target-band-gap candidate screening")

    if predictions.empty:

        st.error(
            "The full screening file was not found. Expected: "
            "results/all_material_predictions.csv"
        )

    else:

        st.write(
            "Search the complete JARVIS-DFT dataset using the selected "
            "target band gap, prediction tolerance, and Random Forest "
            "uncertainty proxy. These are known materials retrospectively "
            "prioritized by the model; this is a screening demonstration, "
            "not a claim of experimental discovery."
        )

        # ----------------------------------------------------
        # SCREENING CONTROLS
        # ----------------------------------------------------

        c1, c2, c3 = st.columns(3)

        target = c1.number_input(
            "Target band gap (eV)",
            min_value=0.0,
            max_value=10.0,
            value=1.5,
            step=0.1,
        )

        max_distance = c2.slider(
            "Maximum predicted distance (eV)",
            min_value=0.01,
            max_value=2.0,
            value=0.10,
            step=0.01,
        )

        max_uncertainty = c3.slider(
            "Maximum uncertainty proxy (eV)",
            min_value=0.01,
            max_value=2.0,
            value=0.40,
            step=0.01,
        )

        # ----------------------------------------------------
        # FILTER MATERIALS
        # ----------------------------------------------------

        df = predictions.copy()

        if (
            "predicted_bandgap" not in df.columns
            or "prediction_uncertainty" not in df.columns
        ):

            st.error(
                "The screening file does not contain the required "
                "'predicted_bandgap' and/or 'prediction_uncertainty' columns."
            )

        else:

            df["distance_from_selected_target"] = (
                df["predicted_bandgap"] - target
            ).abs()

            filtered = df[
                (
                    df["distance_from_selected_target"]
                    <= max_distance
                )
                &
                (
                    df["prediction_uncertainty"]
                    <= max_uncertainty
                )
            ].sort_values(
                [
                    "distance_from_selected_target",
                    "prediction_uncertainty",
                ]
            )

            # ------------------------------------------------
            # RESULT COUNT
            # ------------------------------------------------

            st.success(
                f"Found **{len(filtered):,}** matching materials "
                f"out of **{len(df):,}** total materials."
            )

            # ------------------------------------------------
            # TOP MATCH INFORMATION
            # ------------------------------------------------

            if not filtered.empty:

                m1, m2, m3 = st.columns(3)

                m1.metric(
                    "Closest predicted band gap",
                    f"{filtered.iloc[0]['predicted_bandgap']:.3f} eV",
                )

                if "formula" in filtered.columns:

                    m2.metric(
                        "Closest material",
                        str(filtered.iloc[0]["formula"]),
                    )

                else:

                    m2.metric(
                        "Closest material",
                        "N/A",
                    )

                m3.metric(
                    "Lowest uncertainty",
                    f"{filtered['prediction_uncertainty'].min():.3f} eV",
                )

                # ------------------------------------------------
                # RESULTS TABLE
                # ------------------------------------------------

                display_cols = [
                    "jid",
                    "formula",
                    "predicted_bandgap",
                    "prediction_uncertainty",
                    "target_bandgap",
                    "crys",
                    "spg_number",
                ]

                available = [
                    c
                    for c in display_cols
                    if c in filtered.columns
                ]

                st.markdown("### Matching materials")

                st.dataframe(
                    filtered[available].head(100),
                    use_container_width=True,
                    hide_index=True,
                )

                # ------------------------------------------------
                # BAR CHART
                # ------------------------------------------------

                st.markdown(
                    "### Predicted band gaps of top matches"
                )

                if "formula" in filtered.columns:

                    chart_df = (
                        filtered[
                            [
                                "formula",
                                "predicted_bandgap",
                            ]
                        ]
                        .head(30)
                        .copy()
                    )

                    chart_df["formula"] = (
                        chart_df["formula"].astype(str)
                    )

                    chart_df = chart_df.set_index("formula")

                    st.bar_chart(
                        chart_df,
                        use_container_width=True,
                    )

                # ------------------------------------------------
                # DOWNLOAD
                # ------------------------------------------------

                st.download_button(
                    "Download filtered candidates as CSV",
                    data=filtered.to_csv(
                        index=False
                    ).encode("utf-8"),
                    file_name="filtered_bandgap_candidates.csv",
                    mime="text/csv",
                    use_container_width=True,
                )

            else:

                st.warning(
                    "No materials match the current filters. "
                    "Increase the maximum distance or uncertainty, "
                    "or choose another target band gap."
                )

        # ----------------------------------------------------
        # UNCERTAINTY EXPLANATION
        # ----------------------------------------------------

        st.caption(
            "Uncertainty is the standard deviation of Random Forest "
            "tree predictions and should be treated as a model-dispersion "
            "proxy, not a calibrated prediction interval."
        )


# ============================================================
# TAB 3 — TRUSTWORTHINESS
# ============================================================

with tab3:

    st.subheader("Trustworthiness and interpretation")

    # ========================================================
    # CONFORMAL PREDICTION
    # ========================================================

    if trust:

        st.markdown("### Conformal prediction")

        conformal = trust.get(
            "conformal_prediction",
            {},
        )

        t1, t2, t3 = st.columns(3)

        nominal_coverage = conformal.get(
            "nominal_coverage",
            0,
        )

        observed_coverage = conformal.get(
            "observed_test_coverage",
            0,
        )

        interval_half_width = conformal.get(
            "interval_half_width_eV",
            0,
        )

        t1.metric(
            "Conformal nominal coverage",
            f"{nominal_coverage * 100:.1f}%",
        )

        t2.metric(
            "Observed test coverage",
            f"{observed_coverage * 100:.2f}%",
        )

        t3.metric(
            "Interval half-width",
            f"{interval_half_width:.3f} eV",
        )

        st.info(
            "Conformal intervals are statistical calibration intervals "
            "under their assumptions; they are not physical uncertainty bars."
        )

        interval_width = conformal.get(
            "interval_width_eV",
            None,
        )

        if interval_width is not None:

            st.write(
                f"Full conformal interval width: "
                f"**{interval_width:.3f} eV**"
            )

    else:

        st.info(
            "Run notebooks/06_Trustworthy_ML.ipynb to generate "
            "conformal-calibration and OOD analysis outputs."
        )

    # ========================================================
    # PERMUTATION IMPORTANCE
    # ========================================================

    st.markdown("### Permutation importance")

    if not perm.empty:

        if "importance_mean" in perm.columns:
            importance_col = "importance_mean"

        elif "importance_mae" in perm.columns:
            importance_col = "importance_mae"

        else:
            importance_col = None

        if (
            importance_col is not None
            and "feature" in perm.columns
        ):

            perm_plot = (
                perm.copy()
                .sort_values(
                    importance_col,
                    ascending=False,
                )
                .head(15)
                .sort_values(
                    importance_col,
                    ascending=True,
                )
            )

            chart_df = perm_plot.set_index(
                "feature"
            )[[importance_col]]

            st.bar_chart(
                chart_df,
                use_container_width=True,
            )

            st.caption(
                "Permutation importance measures the change in model "
                "performance when a feature is randomly permuted. "
                "It indicates predictive usefulness, not physical causality."
            )

        else:

            st.warning(
                "Permutation-importance file was found, but the expected "
                "feature or importance column was not recognized."
            )

    else:

        permutation_figure = (
            FIGURES / "top_permutation_importance.svg"
        )

        if permutation_figure.exists():

            st.image(
                str(permutation_figure),
                use_container_width=True,
            )

        else:

            st.info(
                "Permutation-importance results are not available yet."
            )

    # ========================================================
    # SHAP FEATURE IMPORTANCE
    # ========================================================

    st.markdown("### SHAP feature importance")

    if not shap_df.empty:

        if (
            "feature" in shap_df.columns
            and "mean_abs_shap" in shap_df.columns
        ):

            shap_plot = shap_df.copy()

            shap_plot["feature"] = (
                shap_plot["feature"]
                .astype(str)
                .str.replace(
                    "num__",
                    "",
                    regex=False,
                )
                .str.replace(
                    "cat__",
                    "",
                    regex=False,
                )
            )

            shap_plot = shap_plot.sort_values(
                "mean_abs_shap",
                ascending=False,
            )

            top_shap = (
                shap_plot
                .head(15)
                .sort_values(
                    "mean_abs_shap",
                    ascending=True,
                )
            )

            shap_chart = top_shap.set_index(
                "feature"
            )["mean_abs_shap"]

            st.bar_chart(
                shap_chart,
                use_container_width=True,
            )

            st.caption(
                "Mean absolute SHAP value. Larger values indicate "
                "greater average contribution magnitude to model "
                "predictions; they do not imply physical causality."
            )

            with st.expander(
                "View SHAP feature importance values"
            ):

                st.dataframe(
                    shap_plot.head(25),
                    use_container_width=True,
                    hide_index=True,
                )

        else:

            st.warning(
                "SHAP file was found, but the expected columns "
                "'feature' and 'mean_abs_shap' were not found."
            )

    else:

        st.info(
            "SHAP results are not available yet. "
            "Run notebooks/06_Trustworthy_ML.ipynb first."
        )

    # ========================================================
    # APPLICABILITY DOMAIN / OOD
    # ========================================================

    st.markdown(
        "### Applicability-domain / OOD analysis"
    )

    if trust:

        applicability = trust.get(
            "applicability_domain",
            {},
        )

        st.write(
            "The notebook computes nearest-neighbor distance in "
            "standardized numerical descriptor space as an "
            "applicability-domain proxy. Larger distances indicate "
            "weaker support from nearby training examples."
        )

        st.caption(
            "This is an applicability-domain proxy, not a universal "
            "OOD detector."
        )

    else:

        st.write(
            "The planned OOD analysis uses nearest-neighbor distance "
            "in standardized numerical descriptor space."
        )


# ============================================================
# TAB 4 — STRUCTURE-AWARE ML
# ============================================================

with tab4:

    st.subheader("Structure-aware machine learning")

    st.write(
        "Notebook 08 investigates whether adding crystal-structure "
        "descriptors improves band-gap prediction, particularly when "
        "the model is evaluated on chemically unseen material systems."
    )

    st.markdown("### Research question")

    st.info(
        "Does adding structure-aware information improve band-gap "
        "prediction and generalization to chemically unseen systems?"
    )

    # --------------------------------------------------------
    # DESCRIPTOR COMPARISON
    # --------------------------------------------------------

    st.markdown("### Descriptor sets")

    d1, d2 = st.columns(2)

    with d1:

        st.markdown("#### Baseline descriptors")

        st.write(
            "25 composition- and periodic-table-derived descriptors "
            "including electronegativity, ionization energy, "
            "electron affinity, valence information, crystal system, "
            "and space-group number."
        )

    with d2:

        st.markdown("#### Structural descriptors")

        structural_features = [
            "num_sites",
            "volume",
            "volume_per_atom",
            "density",
            "lattice_a",
            "lattice_b",
            "lattice_c",
            "lattice_alpha",
            "lattice_beta",
            "lattice_gamma",
        ]

        st.write(
            ", ".join(structural_features)
        )

    # --------------------------------------------------------
    # CHEMICAL-SYSTEM GROUPKFOLD RESULTS
    # --------------------------------------------------------

    st.markdown(
        "### Chemical-system GroupKFold comparison"
    )

    st.caption(
        "Five-fold GroupKFold keeps chemically related systems "
        "together, providing a stricter test of generalization "
        "to chemically unseen systems."
    )

    comparison = pd.DataFrame(
        {
            "Metric": [
                "MAE (eV)",
                "RMSE (eV)",
                "R²",
            ],
            "Baseline — 25 descriptors": [
                0.3109,
                0.6773,
                0.7324,
            ],
            "Structure-aware — 35 descriptors": [
                0.3044,
                0.6511,
                0.7524,
            ],
        }
    )

    st.dataframe(
        comparison,
        use_container_width=True,
        hide_index=True,
    )

    # --------------------------------------------------------
    # IMPROVEMENT METRICS
    # --------------------------------------------------------

    st.markdown("### Change from adding structural descriptors")

    i1, i2, i3 = st.columns(3)

    i1.metric(
        "MAE",
        "−2.10%",
        help="Relative change in chemical-system GroupKFold MAE.",
    )

    i2.metric(
        "RMSE",
        "−3.86%",
        help="Relative change in chemical-system GroupKFold RMSE.",
    )

    i3.metric(
        "R²",
        "+0.0200",
        help="Absolute increase in chemical-system GroupKFold R².",
    )

    st.success(
        "Structural descriptors improved all three GroupKFold "
        "summary metrics: lower MAE, lower RMSE, and higher R²."
    )

    st.caption(
        "These results provide evidence that structural information "
        "improves predictive generalization in this experiment. "
        "They do not establish a causal physical relationship."
    )

    # --------------------------------------------------------
    # RANDOM-SPLIT COMPARISON
    # --------------------------------------------------------

    st.markdown("### Random-split comparison")

    random_comparison = pd.DataFrame(
        {
            "Metric": [
                "MAE (eV)",
                "RMSE (eV)",
                "R²",
            ],
            "Baseline — 25 descriptors": [
                0.238135,
                0.555889,
                0.819530,
            ],
            "Structure-aware — 35 descriptors": [
                0.246736,
                0.549728,
                0.823508,
            ],
        }
    )

    st.dataframe(
        random_comparison,
        use_container_width=True,
        hide_index=True,
    )

    st.info(
        "On the random split, the structure-aware model has slightly "
        "higher MAE but lower RMSE and slightly higher R². The stronger "
        "evidence for the value of structural descriptors comes from "
        "the stricter chemical-system GroupKFold experiment."
    )

    # --------------------------------------------------------
    # STRUCTURAL FEATURE IMPORTANCE
    # --------------------------------------------------------

    if not structural_importance.empty:

        st.markdown(
            "### Structural feature importance"
        )

        if "feature" in structural_importance.columns:

            possible_importance_columns = [
                "importance_mean",
                "importance_mae",
                "mean_abs_shap",
                "importance",
            ]

            importance_column = None

            for column in possible_importance_columns:

                if column in structural_importance.columns:

                    importance_column = column
                    break

            if importance_column is not None:

                structural_plot = (
                    structural_importance
                    .copy()
                    .sort_values(
                        importance_column,
                        ascending=False,
                    )
                    .head(10)
                    .sort_values(
                        importance_column,
                        ascending=True,
                    )
                )

                st.bar_chart(
                    structural_plot.set_index(
                        "feature"
                    )[[importance_column]],
                    use_container_width=True,
                )

            else:

                st.dataframe(
                    structural_importance.head(20),
                    use_container_width=True,
                    hide_index=True,
                )

        else:

            st.dataframe(
                structural_importance.head(20),
                use_container_width=True,
                hide_index=True,
            )


    # --------------------------------------------------------
    # EXPERIMENT SUMMARY
    # --------------------------------------------------------

    st.markdown("### Notebook 08 experiment summary")

    st.write(
        "The structural descriptors were extracted from the JARVIS-DFT "
        "crystal structures and appended to the existing 25 descriptors. "
        "The combined dataset contains 93,902 materials and 35 predictive "
        "descriptors."
    )

    st.write(
        "The experiment was evaluated using both a standard random split "
        "and a chemical-system GroupKFold split. The latter is the more "
        "challenging test because chemically related systems are prevented "
        "from appearing across training and validation folds."
    )

    st.caption(
        "Structure-aware descriptors: number of sites, cell volume, "
        "volume per atom, density, three lattice lengths, and three "
        "lattice angles."
    )


# ============================================================
# TAB 5 — FINAL MODEL COMPARISON (NOTEBOOK 09)
# ============================================================

with tab5:

    st.subheader("Final research results")

    st.write(
        "Notebook 09 consolidates the final research results, including "
        "random-test performance, chemical-system GroupKFold performance, "
        "structure-aware generalization, trustworthiness, and retrospective "
        "candidate screening."
    )

    if final_model_comparison.empty:

        st.info(
            "Notebook 09 results are not available yet. Run "
            "notebooks/09_Final_Research_Results.ipynb to generate "
            "results/final_model_comparison.csv and "
            "results/final_research_summary.json."
        )

    else:

        st.markdown("### Final model performance comparison")

        st.dataframe(
            final_model_comparison,
            use_container_width=True,
            hide_index=True,
        )

        if {
            "Experiment",
            "MAE (eV)",
        }.issubset(final_model_comparison.columns):

            st.markdown("### MAE comparison")

            mae_plot = (
                final_model_comparison[
                    ["Experiment", "MAE (eV)"]
                ]
                .dropna()
                .set_index("Experiment")
            )

            st.bar_chart(
                mae_plot,
                use_container_width=True,
            )

        if {
            "Experiment",
            "R²",
        }.issubset(final_model_comparison.columns):

            st.markdown("### R² comparison")

            r2_plot = (
                final_model_comparison[
                    ["Experiment", "R²"]
                ]
                .dropna()
                .set_index("Experiment")
            )

            st.bar_chart(
                r2_plot,
                use_container_width=True,
            )

    if not structural_model_comparison.empty:

        st.markdown("### Structure-aware comparison")

        st.dataframe(
            structural_model_comparison,
            use_container_width=True,
            hide_index=True,
        )

    if final_research_summary:

        st.markdown("### Final research summary")

        dataset_summary = final_research_summary.get(
            "dataset",
            {}
        )

        baseline_summary = final_research_summary.get(
            "baseline_model",
            {}
        )

        structure_summary = final_research_summary.get(
            "structure_aware_model",
            {}
        )

        screening_summary = final_research_summary.get(
            "screening",
            {}
        )

        if dataset_summary:

            st.markdown("#### Dataset")

            d1, d2, d3 = st.columns(3)

            d1.metric(
                "Materials",
                f"{dataset_summary.get('materials', 0):,}",
            )

            d2.metric(
                "Target",
                dataset_summary.get(
                    "target",
                    "optb88vdw_bandgap",
                ),
            )

            d3.metric(
                "Units",
                dataset_summary.get(
                    "units",
                    "eV",
                ),
            )

        if baseline_summary:

            st.markdown("#### Baseline model")

            b1, b2, b3 = st.columns(3)

            b1.metric(
                "Random-test MAE",
                f"{baseline_summary.get('random_test_MAE_eV', 0):.4f} eV",
            )

            b2.metric(
                "Random-test RMSE",
                f"{baseline_summary.get('random_test_RMSE_eV', 0):.4f} eV",
            )

            b3.metric(
                "Random-test R²",
                f"{baseline_summary.get('random_test_R2', 0):.4f}",
            )

        if structure_summary:

            st.markdown("#### Structure-aware model")

            s1, s2, s3 = st.columns(3)

            s1.metric(
                "GroupKFold MAE",
                f"{structure_summary.get('groupkfold_MAE_eV', 0):.4f} eV",
            )

            s2.metric(
                "GroupKFold RMSE",
                f"{structure_summary.get('groupkfold_RMSE_eV', 0):.4f} eV",
            )

            s3.metric(
                "GroupKFold R²",
                f"{structure_summary.get('groupkfold_R2', 0):.4f}",
            )

        if screening_summary:

            st.markdown("#### Retrospective screening")

            st.info(
                "Notebook 09 describes this as retrospective candidate "
                "prioritization of known JARVIS-DFT materials, not experimental "
                "discovery."
            )

            screening_table = pd.DataFrame(
                {
                    "Screening quantity": [
                        "Target band gap",
                        "Maximum predicted distance",
                        "Maximum uncertainty proxy",
                        "Matching materials",
                        "Closest material",
                        "Closest predicted band gap",
                    ],
                    "Value": [
                        f"{screening_summary.get('target_bandgap_eV', 0):.2f} eV",
                        f"{screening_summary.get('maximum_distance_eV', 0):.2f} eV",
                        f"{screening_summary.get('maximum_uncertainty_eV', 0):.2f} eV",
                        str(screening_summary.get("matching_materials", 0)),
                        str(screening_summary.get("closest_material", "")),
                        f"{screening_summary.get('closest_predicted_bandgap_eV', 0):.3f} eV",
                    ],
                }
            )

            # Keep the display column Arrow-compatible because it contains
            # text values mixed with numeric values in the source JSON.
            screening_table["Value"] = screening_table["Value"].astype(str)

            st.dataframe(
                screening_table,
                use_container_width=True,
                hide_index=True,
            )


# ============================================================
# TAB 6 — ADVANCED MODEL OPTIMIZATION (NOTEBOOK 10)
# ============================================================

with tab6:

    st.subheader("Advanced model optimization")

    st.write(
        "Notebook 10 evaluates additional model families using the "
        "35-feature structure-enhanced dataset. It compares Random Forest, "
        "Extra Trees, HistGradientBoosting, and a two-stage Extra Trees model."
    )

    if advanced_model_comparison.empty:

        st.info(
            "Notebook 10 results are not available yet. Run "
            "notebooks/10_Advanced_Model_Optimization.ipynb to generate "
            "results/advanced_model_comparison.csv."
        )

    else:

        st.markdown("### Advanced model comparison")

        st.dataframe(
            advanced_model_comparison,
            use_container_width=True,
            hide_index=True,
        )

        if {
            "Model",
            "MAE (eV)",
        }.issubset(advanced_model_comparison.columns):

            st.markdown("### MAE comparison")

            mae_plot = (
                advanced_model_comparison[
                    ["Model", "MAE (eV)"]
                ]
                .dropna()
                .set_index("Model")
            )

            st.bar_chart(
                mae_plot,
                use_container_width=True,
            )

        if {
            "Model",
            "R²",
        }.issubset(advanced_model_comparison.columns):

            st.markdown("### R² comparison")

            r2_plot = (
                advanced_model_comparison[
                    ["Model", "R²"]
                ]
                .dropna()
                .set_index("Model")
            )

            st.bar_chart(
                r2_plot,
                use_container_width=True,
            )

        st.caption(
            "Notebook 10 uses the random test split for this advanced "
            "model-family comparison. Materials-aware GroupKFold remains "
            "the stricter generalization assessment shown elsewhere in "
            "the application."
        )


# ============================================================
# TAB 7 — HYPOTHETICAL COMPOSITION DISCOVERY
# ============================================================

with tab7:

    st.subheader("Hypothetical composition discovery")

    st.write(
        "This extension explores composition space beyond the known "
        "JARVIS-DFT materials. It generates charge-balanced binary and "
        "ternary compositions, removes compositions already represented "
        "in JARVIS-DFT, and ranks the remaining candidates using the "
        "existing Random Forest band-gap model."
    )

    st.warning(
        "These are hypothetical composition candidates, not confirmed "
        "new materials. ML prediction alone does not establish crystal "
        "structure, thermodynamic stability, synthesizability, or "
        "experimental novelty. DFT and structural validation are required."
    )

    if hypothetical_candidates.empty:

        st.info(
            "No hypothetical-candidate file is available yet. Run from "
            "the project root: "
            "python src/generate_hypothetical_candidates.py "
            "--target 1.5 --top-k 200"
        )

    else:

        target = st.number_input(
            "Target predicted band gap (eV)",
            min_value=0.0,
            max_value=10.0,
            value=1.5,
            step=0.1,
            key="hypothetical_target",
        )

        max_distance = st.slider(
            "Maximum distance from target (eV)",
            min_value=0.01,
            max_value=2.0,
            value=0.50,
            step=0.01,
            key="hypothetical_distance",
        )

        max_uncertainty = st.slider(
            "Maximum uncertainty proxy (eV)",
            min_value=0.01,
            max_value=3.0,
            value=1.00,
            step=0.01,
            key="hypothetical_uncertainty",
        )

        df = hypothetical_candidates.copy()

        if {
            "predicted_bandgap_eV",
            "uncertainty_proxy_eV",
        }.issubset(df.columns):

            df["distance_from_selected_target_eV"] = (
                df["predicted_bandgap_eV"] - target
            ).abs()

            filtered = df[
                (df["distance_from_selected_target_eV"] <= max_distance)
                & (df["uncertainty_proxy_eV"] <= max_uncertainty)
            ].sort_values(
                [
                    "distance_from_selected_target_eV",
                    "uncertainty_proxy_eV",
                ]
            )

            c1, c2, c3 = st.columns(3)

            c1.metric("Candidate compositions", f"{len(filtered):,}")
            c2.metric(
                "Closest predicted gap",
                (
                    f"{filtered.iloc[0]['predicted_bandgap_eV']:.3f} eV"
                    if not filtered.empty
                    else "N/A"
                ),
            )
            c3.metric(
                "Lowest uncertainty",
                (
                    f"{filtered['uncertainty_proxy_eV'].min():.3f} eV"
                    if not filtered.empty
                    else "N/A"
                ),
            )

            if not filtered.empty:

                st.markdown("### Ranked hypothetical candidates")

                preferred = [
                    "rank",
                    "formula",
                    "predicted_bandgap_eV",
                    "uncertainty_proxy_eV",
                    "distance_from_target_eV",
                    "screening_score",
                    "num_elements",
                    "total_atoms",
                ]

                cols = [c for c in preferred if c in filtered.columns]

                display = filtered[cols].head(100).copy()

                # Avoid Arrow mixed-type serialization in display tables.
                for col in display.columns:
                    if display[col].dtype == "object":
                        display[col] = display[col].astype(str)

                st.dataframe(
                    display,
                    use_container_width=True,
                    hide_index=True,
                )

                st.markdown("### Predicted band gaps")

                chart_df = (
                    filtered[["formula", "predicted_bandgap_eV"]]
                    .head(30)
                    .copy()
                )
                chart_df["formula"] = chart_df["formula"].astype(str)
                chart_df = chart_df.set_index("formula")

                st.bar_chart(
                    chart_df,
                    use_container_width=True,
                )

                st.download_button(
                    "Download hypothetical candidates",
                    data=filtered.to_csv(index=False).encode("utf-8"),
                    file_name="hypothetical_material_candidates.csv",
                    mime="text/csv",
                    use_container_width=True,
                )

            else:

                st.warning(
                    "No hypothetical candidates match the current "
                    "target, distance, and uncertainty filters."
                )

            st.caption(
                "Important limitation: the hypothetical-candidate model "
                "uses composition-derived descriptors. Crystal system and "
                "space group are unknown for generated compositions, so "
                "this is a composition-space prioritization stage rather "
                "than a structure-aware prediction."
            )

        else:

            st.error(
                "The hypothetical-candidate file is missing the expected "
                "prediction columns. Regenerate it with the discovery script."
            )


# ============================================================
# TAB 8 — ABOUT
# ============================================================

with tab8:

    st.subheader("Project overview")

    st.write(
        "Research question: Can machine learning learn relationships "
        "between chemically and structurally informed descriptors "
        "and DFT-calculated band gaps, then use that model to "
        "prioritize materials for a target range?"
    )

    st.write(
        "Dataset: JARVIS-DFT 3D, 93,902 materials."
    )

    st.write(
        "Target: optb88vdw_bandgap (eV)."
    )

    st.write(
        "Model: Tuned Random Forest Regressor with 200 trees."
    )

    st.write(
        "The baseline descriptor set contains composition-derived "
        "atomic descriptors, electronegativity, ionization energy, "
        "electron affinity, valence information, crystal system, "
        "and space-group information."
    )

    st.write(
        "Notebook 08 extends this representation with structural "
        "descriptors derived from crystal geometry, including unit-cell "
        "volume, density, lattice parameters, and number of sites."
    )

    st.warning(
        "Feature importance indicates predictive usefulness, not "
        "physical causality. The screening results are retrospective "
        "because the materials already exist in the database."
    )

    # --------------------------------------------------------
    # REPRODUCIBILITY
    # --------------------------------------------------------

    st.markdown("### Reproducibility")

    st.write(
        "The notebooks contain the data preparation, validation, "
        "tuning, screening, structural analysis, and interpretation "
        "workflow. The all-material screening predictions are generated "
        "by src/generate_screening_predictions.py."
    )

    # --------------------------------------------------------
    # PROJECT COMPONENTS
    # --------------------------------------------------------

    st.markdown("### Main workflow")

    st.write(
        "JARVIS-DFT data → descriptor engineering → "
        "Random Forest regression → materials-aware validation → "
        "trustworthiness analysis → structural generalization → "
        "candidate screening"
    )


# ============================================================
# SIDEBAR
# ============================================================

st.sidebar.header("Project")

st.sidebar.write(
    "Quantum Materials + Machine Learning"
)

st.sidebar.write(
    "JARVIS-DFT 3D"
)

st.sidebar.write(
    "Target: OptB88vdW band gap"
)

st.sidebar.markdown(
    "[GitHub repository]"
    "(https://github.com/ay23-byte/"
    "Quantum_materials_assited_machine_learning)"
)