import json
from pathlib import Path

import pandas as pd
import streamlit as st


# ============================================================
# PROJECT PATHS
# ============================================================

ROOT = Path(__file__).resolve().parent
RESULTS = ROOT / "results"
FIGURES = ROOT / "figures"


# ============================================================
# STREAMLIT CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="Quantum Materials ML",
    page_icon="🔬",
    layout="wide",
)


# ============================================================
# DATA LOADING FUNCTIONS
# ============================================================

@st.cache_data
def load_predictions():
    """
    Load predictions generated by the all-material screening script.
    """
    path = RESULTS / "all_material_predictions.csv"

    if not path.exists():
        return pd.DataFrame()

    return pd.read_csv(path)


@st.cache_data
def load_metrics():
    """
    Load final model test metrics.
    """
    path = RESULTS / "final_model_metrics.json"

    if not path.exists():
        return {}

    try:
        return json.loads(path.read_text())
    except Exception:
        return {}


@st.cache_data
def load_group_metrics():
    """
    Load chemical-system GroupKFold validation metrics.
    """
    path = RESULTS / "tuned_groupkfold_summary.json"

    if not path.exists():
        return {}

    try:
        return json.loads(path.read_text())
    except Exception:
        return {}


@st.cache_data
def load_trustworthiness():
    """
    Load trustworthy-ML summary generated by Notebook 06.
    """
    path = RESULTS / "advanced_trustworthiness_summary.json"

    if not path.exists():
        return {}

    try:
        return json.loads(path.read_text())
    except Exception:
        return {}


@st.cache_data
def load_permutation_importance():
    """
    Load permutation feature importance.
    """
    path = RESULTS / "advanced_permutation_importance.csv"

    if not path.exists():
        return pd.DataFrame()

    try:
        return pd.read_csv(path)
    except Exception:
        return pd.DataFrame()


@st.cache_data
def load_shap_importance():
    """
    Load SHAP feature importance.
    """
    path = RESULTS / "shap_feature_importance.csv"

    if not path.exists():
        return pd.DataFrame()

    try:
        return pd.read_csv(path)
    except Exception:
        return pd.DataFrame()


# ============================================================
# LOAD PROJECT DATA
# ============================================================

metrics = load_metrics()
group_metrics = load_group_metrics()
predictions = load_predictions()

trust = load_trustworthiness()
perm = load_permutation_importance()
shap_df = load_shap_importance()


# ============================================================
# HEADER
# ============================================================

st.title(
    "Machine-Learning-Assisted Discovery of Quantum Materials"
)

st.caption(
    "JARVIS-DFT 3D • OptB88vdW band-gap prediction • Random Forest"
)


# ============================================================
# TABS
# ============================================================

tab1, tab2, tab3, tab4 = st.tabs(
    [
        "Model performance",
        "Candidate screening",
        "Trustworthiness",
        "About",
    ]
)


# ============================================================
# TAB 1 — MODEL PERFORMANCE
# ============================================================

with tab1:

    st.subheader("Final model performance")

    c1, c2, c3 = st.columns(3)

    c1.metric(
        "Test MAE",
        f"{metrics.get('test_MAE_eV', 0):.3f} eV",
    )

    c2.metric(
        "Test RMSE",
        f"{metrics.get('test_RMSE_eV', 0):.3f} eV",
    )

    c3.metric(
        "Test R²",
        f"{metrics.get('test_R2', 0):.3f}",
    )

    # --------------------------------------------------------
    # MATERIALS-AWARE VALIDATION
    # --------------------------------------------------------

    st.markdown("### Materials-aware validation")

    g1, g2, g3 = st.columns(3)

    g1.metric(
        "GroupKFold MAE",
        f"{group_metrics.get('MAE_mean_eV', 0):.3f} ± "
        f"{group_metrics.get('MAE_std_eV', 0):.3f} eV",
    )

    g2.metric(
        "GroupKFold RMSE",
        f"{group_metrics.get('RMSE_mean_eV', 0):.3f} ± "
        f"{group_metrics.get('RMSE_std_eV', 0):.3f} eV",
    )

    g3.metric(
        "GroupKFold R²",
        f"{group_metrics.get('R2_mean', 0):.3f} ± "
        f"{group_metrics.get('R2_std', 0):.3f}",
    )

    st.info(
        "The random test split measures interpolation on a held-out "
        "subset. Chemical-system GroupKFold is stricter: related "
        "chemical systems are kept out of the training fold."
    )

    # --------------------------------------------------------
    # MODEL DESCRIPTION
    # --------------------------------------------------------

    st.markdown("### What the model predicts")

    st.write(
        "The model predicts the JARVIS-DFT OptB88vdW band gap in eV "
        "using composition-derived atomic descriptors and "
        "crystal-structure information. HSE/MBJ band gaps are not "
        "used as input features."
    )


# ============================================================
# TAB 2 — CANDIDATE SCREENING
# ============================================================

with tab2:

    st.subheader("Target-band-gap candidate screening")

    if predictions.empty:

        st.error(
            "The full screening file was not found. Expected: "
            "results/all_material_predictions.csv"
        )

    else:

        st.write(
            "Search the complete JARVIS-DFT dataset using the selected "
            "target band gap, prediction tolerance, and Random Forest "
            "uncertainty proxy. These are known materials retrospectively "
            "prioritized by the model; this is a screening demonstration, "
            "not a claim of experimental discovery."
        )

        # ----------------------------------------------------
        # SCREENING CONTROLS
        # ----------------------------------------------------

        c1, c2, c3 = st.columns(3)

        target = c1.number_input(
            "Target band gap (eV)",
            min_value=0.0,
            max_value=10.0,
            value=1.5,
            step=0.1,
        )

        max_distance = c2.slider(
            "Maximum predicted distance (eV)",
            min_value=0.01,
            max_value=2.0,
            value=0.10,
            step=0.01,
        )

        max_uncertainty = c3.slider(
            "Maximum uncertainty proxy (eV)",
            min_value=0.01,
            max_value=2.0,
            value=0.40,
            step=0.01,
        )

        # ----------------------------------------------------
        # FILTER MATERIALS
        # ----------------------------------------------------

        df = predictions.copy()

        if (
            "predicted_bandgap" not in df.columns
            or "prediction_uncertainty" not in df.columns
        ):

            st.error(
                "The screening file does not contain the required "
                "'predicted_bandgap' and/or 'prediction_uncertainty' columns."
            )

        else:

            df["distance_from_selected_target"] = (
                df["predicted_bandgap"] - target
            ).abs()

            filtered = df[
                (
                    df["distance_from_selected_target"]
                    <= max_distance
                )
                &
                (
                    df["prediction_uncertainty"]
                    <= max_uncertainty
                )
            ].sort_values(
                [
                    "distance_from_selected_target",
                    "prediction_uncertainty",
                ]
            )

            # ------------------------------------------------
            # RESULT COUNT
            # ------------------------------------------------

            st.success(
                f"Found **{len(filtered):,}** matching materials "
                f"out of **{len(df):,}** total materials."
            )

            # ------------------------------------------------
            # TOP MATCH INFORMATION
            # ------------------------------------------------

            if not filtered.empty:

                m1, m2, m3 = st.columns(3)

                m1.metric(
                    "Closest predicted band gap",
                    f"{filtered.iloc[0]['predicted_bandgap']:.3f} eV",
                )

                if "formula" in filtered.columns:

                    m2.metric(
                        "Closest material",
                        str(filtered.iloc[0]["formula"]),
                    )

                else:

                    m2.metric(
                        "Closest material",
                        "N/A",
                    )

                m3.metric(
                    "Lowest uncertainty",
                    f"{filtered['prediction_uncertainty'].min():.3f} eV",
                )

                # ------------------------------------------------
                # RESULTS TABLE
                # ------------------------------------------------

                display_cols = [
                    "jid",
                    "formula",
                    "predicted_bandgap",
                    "prediction_uncertainty",
                    "target_bandgap",
                    "crys",
                    "spg_number",
                ]

                available = [
                    c
                    for c in display_cols
                    if c in filtered.columns
                ]

                st.markdown("### Matching materials")

                st.dataframe(
                    filtered[available].head(100),
                    width="stretch",
                    hide_index=True,
                )

                # ------------------------------------------------
                # BAR CHART
                # ------------------------------------------------

                st.markdown(
                    "### Predicted band gaps of top matches"
                )

                if "formula" in filtered.columns:

                    chart_df = (
                        filtered[
                            [
                                "formula",
                                "predicted_bandgap",
                            ]
                        ]
                        .head(30)
                        .copy()
                    )

                    chart_df["formula"] = (
                        chart_df["formula"].astype(str)
                    )

                    chart_df = chart_df.set_index("formula")

                    st.bar_chart(
                        chart_df,
                        width="stretch",
                    )

                # ------------------------------------------------
                # DOWNLOAD
                # ------------------------------------------------

                st.download_button(
                    "Download filtered candidates as CSV",
                    data=filtered.to_csv(
                        index=False
                    ).encode("utf-8"),
                    file_name="filtered_bandgap_candidates.csv",
                    mime="text/csv",
                    width="stretch",
                )

            else:

                st.warning(
                    "No materials match the current filters. "
                    "Increase the maximum distance or uncertainty, "
                    "or choose another target band gap."
                )

        # ----------------------------------------------------
        # UNCERTAINTY EXPLANATION
        # ----------------------------------------------------

        st.caption(
            "Uncertainty is the standard deviation of Random Forest "
            "tree predictions and should be treated as a model-dispersion "
            "proxy, not a calibrated prediction interval."
        )


# ============================================================
# TAB 3 — TRUSTWORTHINESS
# ============================================================

with tab3:

    st.subheader("Trustworthiness and interpretation")

    # ========================================================
    # CONFORMAL PREDICTION
    # ========================================================

    if trust:

        st.markdown("### Conformal prediction")

        # Notebook 06 stores conformal values inside
        # the "conformal_prediction" dictionary.

        conformal = trust.get(
            "conformal_prediction",
            {},
        )

        t1, t2, t3 = st.columns(3)

        nominal_coverage = conformal.get(
            "nominal_coverage",
            0,
        )

        observed_coverage = conformal.get(
            "observed_test_coverage",
            0,
        )

        interval_half_width = conformal.get(
            "interval_half_width_eV",
            0,
        )

        t1.metric(
            "Conformal nominal coverage",
            f"{nominal_coverage * 100:.1f}%",
        )

        t2.metric(
            "Observed test coverage",
            f"{observed_coverage * 100:.2f}%",
        )

        t3.metric(
            "Interval half-width",
            f"{interval_half_width:.3f} eV",
        )

        st.info(
            "Conformal intervals are statistical calibration intervals "
            "under their assumptions; they are not physical uncertainty bars."
        )

        # Optional additional information

        interval_width = conformal.get(
            "interval_width_eV",
            None,
        )

        if interval_width is not None:

            st.write(
                f"Full conformal interval width: "
                f"**{interval_width:.3f} eV**"
            )

    else:

        st.info(
            "Run notebooks/06_Trustworthy_ML.ipynb to generate "
            "conformal-calibration and OOD analysis outputs."
        )

    # ========================================================
    # PERMUTATION IMPORTANCE
    # ========================================================

    st.markdown("### Permutation importance")

    if not perm.empty:

        # Notebook versions may use different column names.
        # Prefer importance_mean when available.

        if "importance_mean" in perm.columns:

            importance_col = "importance_mean"

        elif "importance_mae" in perm.columns:

            importance_col = "importance_mae"

        else:

            importance_col = None

        if (
            importance_col is not None
            and "feature" in perm.columns
        ):

            perm_plot = (
                perm.copy()
                .sort_values(
                    importance_col,
                    ascending=False,
                )
                .head(15)
                .sort_values(
                    importance_col,
                    ascending=True,
                )
            )

            chart_df = perm_plot.set_index(
                "feature"
            )[[importance_col]]

            st.bar_chart(
                chart_df,
                width="stretch",
            )

            st.caption(
                "Permutation importance measures the change in model "
                "performance when a feature is randomly permuted. "
                "It indicates predictive usefulness, not physical causality."
            )

        else:

            st.warning(
                "Permutation-importance file was found, but the expected "
                "feature or importance column was not recognized."
            )

    else:

        # Fallback to the older SVG figure if it exists.

        permutation_figure = (
            FIGURES / "top_permutation_importance.svg"
        )

        if permutation_figure.exists():

            st.image(
                str(permutation_figure),
                width="stretch",
            )

        else:

            st.info(
                "Permutation-importance results are not available yet."
            )

    # ========================================================
    # SHAP FEATURE IMPORTANCE
    # ========================================================

    st.markdown("### SHAP feature importance")

    if not shap_df.empty:

        if (
            "feature" in shap_df.columns
            and "mean_abs_shap" in shap_df.columns
        ):

            shap_plot = shap_df.copy()

            # Remove sklearn Pipeline prefixes.

            shap_plot["feature"] = (
                shap_plot["feature"]
                .astype(str)
                .str.replace(
                    "num__",
                    "",
                    regex=False,
                )
                .str.replace(
                    "cat__",
                    "",
                    regex=False,
                )
            )

            # Sort by mean absolute SHAP value.

            shap_plot = shap_plot.sort_values(
                "mean_abs_shap",
                ascending=False,
            )

            # Top 15 for visualization.

            top_shap = (
                shap_plot
                .head(15)
                .sort_values(
                    "mean_abs_shap",
                    ascending=True,
                )
            )

            shap_chart = top_shap.set_index(
                "feature"
            )["mean_abs_shap"]

            st.bar_chart(
                shap_chart,
                width="stretch",
            )

            st.caption(
                "Mean absolute SHAP value. Larger values indicate "
                "greater average contribution magnitude to model "
                "predictions; they do not imply physical causality."
            )

            # ------------------------------------------------
            # FULL SHAP TABLE
            # ------------------------------------------------

            with st.expander(
                "View SHAP feature importance values"
            ):

                st.dataframe(
                    shap_plot.head(25),
                    width="stretch",
                    hide_index=True,
                )

        else:

            st.warning(
                "SHAP file was found, but the expected columns "
                "'feature' and 'mean_abs_shap' were not found."
            )

    else:

        st.info(
            "SHAP results are not available yet. "
            "Run notebooks/06_Trustworthy_ML.ipynb first."
        )

    # ========================================================
    # APPLICABILITY DOMAIN / OOD
    # ========================================================

    st.markdown(
        "### Applicability-domain / OOD analysis"
    )

    if trust:

        applicability = trust.get(
            "applicability_domain",
            {},
        )

        st.write(
            "The notebook computes nearest-neighbor distance in "
            "standardized numerical descriptor space as an "
            "applicability-domain proxy. Larger distances indicate "
            "weaker support from nearby training examples."
        )

        st.caption(
            "This is an applicability-domain proxy, not a universal "
            "OOD detector."
        )

    else:

        st.write(
            "The planned OOD analysis uses nearest-neighbor distance "
            "in standardized numerical descriptor space."
        )


# ============================================================
# TAB 4 — ABOUT
# ============================================================

with tab4:

    st.subheader("Project overview")

    st.write(
        "Research question: Can machine learning learn relationships "
        "between chemically and structurally informed descriptors "
        "and DFT-calculated band gaps, then use that model to "
        "prioritize materials for a target range?"
    )

    st.write(
        "Dataset: JARVIS-DFT 3D, 93,902 materials."
    )

    st.write(
        "Target: optb88vdw_bandgap (eV)."
    )

    st.write(
        "Model: Tuned Random Forest Regressor with 200 trees."
    )

    st.write(
        "Descriptors include composition statistics, "
        "electronegativity, ionization energy, electron affinity, "
        "valence information, periodic-table descriptors, crystal "
        "system, and space-group number."
    )

    st.warning(
        "Feature importance indicates predictive usefulness, not "
        "physical causality. The screening results are retrospective "
        "because the materials already exist in the database."
    )

    # ========================================================
    # REPRODUCIBILITY
    # ========================================================

    st.markdown("### Reproducibility")

    st.write(
        "The notebooks contain the data preparation, validation, "
        "tuning, screening, and interpretation workflow. The "
        "all-material screening predictions are generated by "
        "src/generate_screening_predictions.py."
    )

    # ========================================================
    # PROJECT COMPONENTS
    # ========================================================

    st.markdown("### Main workflow")

    st.write(
        "JARVIS-DFT data → descriptor engineering → "
        "Random Forest regression → materials-aware validation → "
        "trustworthiness analysis → candidate screening"
    )


# ============================================================
# SIDEBAR
# ============================================================

st.sidebar.header("Project")

st.sidebar.write(
    "Quantum Materials + Machine Learning"
)

st.sidebar.write(
    "JARVIS-DFT 3D"
)

st.sidebar.write(
    "Target: OptB88vdW band gap"
)

st.sidebar.markdown(
    "[GitHub repository]"
    "(https://github.com/ay23-byte/"
    "Quantum_materials_assited_machine_learning)"
)