"""Prepare validated hypothetical structures for downstream DFT calculations.

This stage does not run DFT. It packages validated POSCARs into reproducible
job folders with conservative VASP starting templates and provenance.
POTCAR files are intentionally not generated because they depend on the
user's licensed pseudopotential library.
"""

from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
VALIDATION_FILE = ROOT / "results" / "hypothetical_structures" / "structure_validation.csv"
DEFAULT_OUTPUT = ROOT / "results" / "dft_jobs"

INCAR = """SYSTEM = {formula} prototype {prototype_index}
ENCUT = 520
PREC = Accurate
EDIFF = 1E-6
EDIFFG = -0.02
IBRION = 2
ISIF = 3
NSW = 200
ISMEAR = 0
SIGMA = 0.05
LREAL = Auto
LASPH = .TRUE.
ADDGRID = .TRUE.
LWAVE = .FALSE.
LCHARG = .FALSE.

# Starting-point relaxation template only.
# Verify ENCUT, POTCAR compatibility, magnetic settings, and dispersion
# treatment against the final production methodology.
"""

KPOINTS = """Automatic mesh for initial relaxation
0
Gamma
{ka} {kb} {kc}
0 0 0
"""

README = """# DFT job preparation: {formula} / prototype {prototype_index}

This directory contains a **DFT-ready starting package** for a hypothetical
composition generated by the prototype-transfer workflow.

## Provenance

- Formula: `{formula}`
- Shortlist rank: {rank}
- Prototype source: `{jid}` ({source_formula})
- Prototype class: `{prototype}`
- Lattice scaling factor: {scale:.3f}
- Structural validation: `{status}`
- Validation warnings: {warnings}

## Files

- `POSCAR`: prototype-transferred initial structure.
- `INCAR.template`: conservative VASP relaxation starting template.
- `KPOINTS.template`: Gamma-centered starting mesh.
- `metadata.json`: provenance and validation information.

A `POTCAR` is **not** included. Generate it from the appropriate licensed
pseudopotential set and verify that every element in POSCAR is covered.

## Scientific status

This is an **initial structure for DFT relaxation**, not a relaxed structure.
Prototype transfer does not establish the ground-state structure,
thermodynamic stability, dynamical stability, synthesizability, or
experimental realizability.

Recommended next steps:

1. Inspect POSCAR and chemical environment.
2. Generate and verify POTCARs.
3. Run geometry relaxation.
4. Check convergence and relaxed geometry.
5. Calculate formation energy / energy above hull consistently.
6. Calculate electronic structure and band gap for selected candidates.
7. Consider phonon or other dynamical-stability calculations where justified.

If validation reports a warning, inspect that structure before production DFT.
"""

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Prepare validated hypothetical structures for DFT.")
    p.add_argument("--validation-file", type=Path, default=VALIDATION_FILE)
    p.add_argument("--output-root", type=Path, default=DEFAULT_OUTPUT)
    p.add_argument("--status", choices=["all", "valid", "valid_with_warnings"], default="all")
    return p.parse_args()

def kpoint_mesh(row: pd.Series) -> tuple[int, int, int]:
    lengths = []
    for key in ("a_A", "b_A", "c_A"):
        try:
            value = float(row[key])
        except (TypeError, ValueError):
            value = 10.0
        lengths.append(max(value, 1.0))
    # Initial ~0.25 1/Angstrom reciprocal sampling; convergence must be tested.
    return tuple(max(1, min(8, round(25.0 / length))) for length in lengths)

def root_path(value: Path) -> Path:
    return value if value.is_absolute() else ROOT / value

def prepare(row: pd.Series, output_root: Path) -> dict:
    formula = str(row["formula"])
    idx = int(row["prototype_index"])
    source = root_path(Path(str(row["poscar"])))
    if not source.exists():
        raise FileNotFoundError(f"POSCAR not found: {source}")

    job = output_root / formula / f"prototype_{idx}"
    job.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, job / "POSCAR")

    ka, kb, kc = kpoint_mesh(row)
    (job / "INCAR.template").write_text(
        INCAR.format(formula=formula, prototype_index=idx), encoding="utf-8"
    )
    (job / "KPOINTS.template").write_text(
        KPOINTS.format(ka=ka, kb=kb, kc=kc), encoding="utf-8"
    )

    warnings = str(row.get("warnings", "")).strip()
    if not warnings or warnings.lower() == "nan":
        warnings = "none"

    metadata = {
        "formula": formula,
        "shortlist_rank": int(row["shortlist_rank"]),
        "prototype_index": idx,
        "prototype_source_jid": str(row["prototype_source_jid"]),
        "prototype_source_formula": str(row["prototype_source_formula"]),
        "prototype": str(row["prototype"]),
        "lattice_scale": float(row["lattice_scale"]),
        "validation_status": str(row["status"]),
        "validation_warnings": warnings,
        "kpoint_mesh_gamma": [ka, kb, kc],
        "scientific_status": "prototype-transferred initial structure; not relaxed or stability-validated",
    }
    (job / "metadata.json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")
    (job / "README.txt").write_text(
        README.format(
            formula=formula, prototype_index=idx, rank=int(row["shortlist_rank"]),
            jid=row["prototype_source_jid"], source_formula=row["prototype_source_formula"],
            prototype=row["prototype"], scale=float(row["lattice_scale"]),
            status=row["status"], warnings=warnings
        ),
        encoding="utf-8",
    )

    rel = lambda p: str(p.relative_to(ROOT))
    return {
        "formula": formula,
        "prototype_index": idx,
        "validation_status": str(row["status"]),
        "prototype_source_jid": str(row["prototype_source_jid"]),
        "prototype_source_formula": str(row["prototype_source_formula"]),
        "lattice_scale": float(row["lattice_scale"]),
        "kpoints": f"{ka} {kb} {kc}",
        "job_directory": rel(job),
        "poscar": rel(job / "POSCAR"),
        "incar_template": rel(job / "INCAR.template"),
        "kpoints_template": rel(job / "KPOINTS.template"),
        "warnings": warnings,
    }

def main() -> None:
    args = parse_args()
    validation_file = root_path(args.validation_file)
    output_root = root_path(args.output_root)

    if not validation_file.exists():
        raise FileNotFoundError(
            f"Validation file not found: {validation_file}. Run structure validation first."
        )

    df = pd.read_csv(validation_file)
    df = df[df["status"].isin(["valid", "valid_with_warnings"])].copy()
    if args.status != "all":
        df = df[df["status"] == args.status].copy()
    if df.empty:
        raise RuntimeError("No structures match the requested validation status.")

    output_root.mkdir(parents=True, exist_ok=True)
    print(f"Structures to prepare: {len(df)}")

    rows = []
    for _, row in df.iterrows():
        print(f"Preparing {row['formula']} / prototype {int(row['prototype_index'])}...")
        rows.append(prepare(row, output_root))
        print("  [OK] DFT starting package prepared")

    manifest = pd.DataFrame(rows)
    manifest_file = output_root / "dft_job_manifest.csv"
    summary_file = output_root / "dft_job_summary.json"
    manifest.to_csv(manifest_file, index=False)

    summary = {
        "source_validation_file": str(validation_file.relative_to(ROOT)),
        "output_root": str(output_root.relative_to(ROOT)),
        "prepared_structures": len(manifest),
        "valid": int((manifest["validation_status"] == "valid").sum()),
        "valid_with_warnings": int((manifest["validation_status"] == "valid_with_warnings").sum()),
        "potcar_generated": False,
        "interpretation": (
            "DFT input preparation only. POSCARs are prototype-transferred initial structures. "
            "INCAR/KPOINTS are starting templates and require convergence/methodology checks."
        ),
        "manifest_file": str(manifest_file.relative_to(ROOT)),
    }
    summary_file.write_text(json.dumps(summary, indent=2), encoding="utf-8")

    print("\nDFT job preparation complete.")
    print(f"Prepared: {summary['prepared_structures']}")
    print(f"Valid: {summary['valid']}")
    print(f"Valid with warnings: {summary['valid_with_warnings']}")
    print(f"Manifest: {manifest_file}")
    print(f"Summary: {summary_file}")

if __name__ == "__main__":
    main()
